### PR TITLE
fix(web): court-ongoing-stats

### LINKED ISSUE #1193: Court stats: incorrect number of cases in progress
Expected: 0
Actual: 12

https://v2.kleros.builders/#/courts/1/purpose

image

### PR DESCRIPTION
**Pull request by nhestrompia**
closes #1193

### CODE REVIEW

**Comment by jaybuidl** [comment]
⚠️ It requires a redeploy of the testnet subgraph

**Review by jaybuidl — COMMENTED** [review]
Getting an error during gql generation

```bash
```

**Comment by jaybuidl** [comment]
Depends on the filtering PR changes #1169

**Comment by kemuru** [comment]
fixed in #1332

**Pull request closed without merging**
