### PR TITLE
Feat(subgraph): Add fields to ease dashboard tracking.

### PR DESCRIPTION
**Pull request by alcercu**

### CODE REVIEW

**Comment by alcercu** [comment]
Solves #586

**Review by unknownunknown1 — APPROVED** [review]

**Comment by unknownunknown1** [comment]
Can't fully attest to changes in typescript, but contract changes look good

**Review by jaybuidl — DISMISSED** [review]

**Comment by jaybuidl** [comment]
Related to #264

**Review by jaybuidl — DISMISSED** [review]

**Review by jaybuidl — APPROVED** [review]

**Review by jaybuidl — APPROVED** [review]

**Review by jaybuidl — APPROVED** [review]

**Review by jaybuidl — DISMISSED** [review]

**Review by jaybuidl — DISMISSED** [review]

**Review by jaybuidl — APPROVED** [review]

**Comment by jaybuidl** [comment]
The frontend update can be addressed in a separate PR.

**Pull request merged**
