### PR TITLE
Add commit reveal support

### PR DESCRIPTION
**Pull request by alcercu**
## PR-Codex overview
This PR focuses on adding new features and making improvements to the codebase. 

### Detailed summary:
- Added `isUndefined` function to `utils/index.ts`
- Added `catchShortMessage` function to `utils/index.ts`
- Added `useIsDesktop` hook to `hooks/useIsDesktop.tsx`
- Updated `isLastRound` function in `utils/isLastRound.ts`
- Added `InfoCard` component to `components/InfoCard.tsx`
- Added `PendingVotesBox` component to `pages/Cases/CaseDetails/Voting/PendingVotesBox.tsx`
- Added `JustificationArea` component to `pages/Cases/CaseDetails/Voting/Classic/JustificationArea.tsx`
- Updated `HeroImage` component in `components/HeroImage.tsx`
- Updated `contactDetails` function in `consts/eip712-messages.ts`
- Updated `VoteWithCommitExtraInfo` component in `components/Popup/ExtraInfo/VoteWithCommitExtraInfo.tsx`
- Added `useSigningAccount` hook to `hooks/useSigningAccount.tsx`
- Updated `Filters` component in `components/CasesDisplay/Filters.tsx`
- Updated `CasesGrid` component in `components/CasesDisplay/CasesGrid.tsx`
- Updated `CasesFetcher` component in `pages/Cases/CasesFetcher.tsx`

> The following files were skipped due to too many changes: `web/src/pages/Cases/CasesFetcher.tsx`, `web/src/pages/Cases/CaseDetails/Voting/Classic/index.tsx`, `web/src/pages/Cases/CaseDetails/Voting/Classic/Vote.tsx`, `web/src/pages/Cases/CaseDetails/Voting/VotingHistory.tsx`, `web/src/pages/Cases/CaseDetails/Voting/Classic/OptionsContainer.tsx`, `web/src/pages/Cases/CaseDetails/Voting/Classic/Commit.tsx`, `web/src/pages/Cases/CaseDetails/Timeline.tsx`, `web/src/pages/Cases/CaseDetails/Voting/Classic/Reveal.tsx`, `web/src/pages/Cases/CaseDetails/Voting/index.tsx`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Review by kemuru — COMMENTED** [review]
code is looking good, but for some reason the Commit voting options' buttons are not working?

https://github.com/kleros/kleros-v2/assets/102478601/e34a6dad-f163-416f-8205-27234a1fd3e0

**Comment by alcercu** [comment]
> code is looking good, but for some reason the Commit voting options' buttons are not working?
> 
>  2024-01-09.20-15-59.mp4 
> I then tested creating a case in a court without Commit/reveal activated, voting directly works good:
> 
>  2024-01-09.23-18-29.mp4

It works for me 🤔 did it prompt you to sign a message? try deleting the localstorage

**Comment by kemuru** [comment]
> > code is looking good, but for some reason the Commit voting options' buttons are not working?
> > 2024-01-09.20-15-59.mp4
> > I then tested creating a case in a court without Commit/reveal activated, voting directly works good:
> > 2024-01-09.23-18-29.mp4
> 
> It works for me 🤔 did it prompt you to sign a message? try deleting the localstorage

yep I tried deleting localStorage and same problem. I now spotted this error in the console:

image

**Comment by kemuru** [comment]
Got this error when voting one option, and then because the subgraph was really slow I was able to click on another option which maybe was saved in localStorage and then at the time of reveal it errored since the options didn't match (but worked when deleting localStorage since it bruteforced the choice)

image

**Review by jaybuidl — APPROVED** [review]

**Pull request merged**
