### PR TITLE
fix(web): links to socials

### LINKED ISSUE #648: lots of "www.google.com" (this is fine to hardcode, but putting the correct website urls) on consts/community-elements

### PR DESCRIPTION
**Pull request by Arun9650**
close #648
i have put all the links but only 2 left as I have not found the links one is "join the community calls" and cooperative kleros.

### CODE REVIEW

**Comment by kemuru** [comment]
hey mate, I mentioned all the correct links a while ago, you can find them here:
https://github.com/kleros/kleros-v2/issues/625

for your convenience i'll paste them again:

correct links, respectively:

https://forum.kleros.io/
https://snapshot.org/#/kleros.eth/
https://kleros.io/coop/
https://t.me/kleros
https://discord.com/invite/cAvWk8B23f
https://t.me/kleros
https://slack.kleros.io/

(Add them, push again, and I will merge it)

**Comment by Arun9650** [comment]
> 

and for the community calls, is this the link https://kleros.io/community ?

**Comment by kemuru** [comment]
AFAIK the community calls are done in Telegram

**Review by kemuru — DISMISSED** [review]
One detail, to be able to merge in kleros-v2 it is necessary that all the commits in the PR have been signed. To sign commits, you must register a GPG key in Github and to sign previous commits, you must do a rebase. Here are some links that might help you:

Adding a GPG key to your Github account: https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account
Generating a new GPG key: https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key
If you are on a branch other than master:
git rebase --exec 'git commit --amend --no-edit -n -S' -i master

If you are on master (where N is the number of commits you want to sign):
git rebase -i HEAD~N

Then, if the changes were already on the remote, to force push:
git push --force-with-lease.

**Comment by kemuru** [comment]
One detail, to be able to merge in kleros-v2 it is necessary that all the commits in the PR have been signed. To sign commits, you must register a GPG key in Github and to sign previous commits, you must do a rebase. Here are some links that might help you:

Adding a GPG key to your Github account: https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account
Generating a new GPG key: https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key
If you are on a branch other than master:
git rebase --exec 'git commit --amend --no-edit -n -S' -i master

If you are on master (where N is the number of commits you want to sign):
git rebase -i HEAD~N

Then, if the changes were already on the remote, to force push:
git push --force-with-lease.

**Comment by Arun9650** [comment]
hey mate, I do all the steps but it says everything is up to date. I don't know why it is saying that
image

**Review by jaybuidl — APPROVED** [review]

**Pull request merged**
