### PR TITLE
feat(web): add-enhanced-number-display-component

### LINKED ISSUE #1427: Web: dynamic decimals
Don't show unnecessary decimals when last decimals end in "0", that is, they do not provide extra information. So, show decimals by default (up to a certain number of decimals, for example, 2) but if the last decimals are all zeros, the decimals do not appear because they do not provide extra information.

(note, in the second example in reality I have ETH rewards, its something like 0.00002 ETH, but since it's capped to 3 decimals its showing 0, so maybe fix that too).

Screenshot 2024-01-19 at 10 50 15
Screenshot 2024-01-19 at 10 51 51

### PR DESCRIPTION
**Pull request by Harman-singh-waraich**
closes #1427 

- Adds `NumberDisplay` component, that displays the number up to  specified decimals, the precise value is shown in a tooltip when hovered.
- Added in places where user might want to see precise values, (Dashboard, Top Jurors Rewards Display)
Screenshot 2024-01-22 at 18 15 41
Screenshot 2024-01-22 at 18 16 15

---

### Detailed summary:

- Added a new component `NumberDisplay` for displaying numbers with optional units and tooltips.
- Updated multiple files to use the `NumberDisplay` component instead of directly displaying numbers.
- Replaced the display of stake and rewards values with `NumberDisplay` in the `CourtCard`, `Rewards`, `Header`, and `TokenRewards` components.
- Modified the `getAmount` and `getValue` functions in `jurorRewardConfig.ts` to return formatted numbers using `formatEther` and `formatUnits` functions.
- Updated the `getFormattedRewards` function in `jurorRewardConfig.ts` to use the correct coin price based on the token.
- Imported `Tooltip` component from `@kleros/ui-components-library` in the `NumberDisplay` component.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Review by alcercu — CHANGES_REQUESTED** [review]
looks good, but I think it would look even better if we keep the units in the tooltip too 🤔 like `0.08 ETH` then you hover and you see `0.078 ETH` on the hover tooltip too 🤔

**Review by kemuru — CHANGES_REQUESTED** [review]
when I hover on the ETH reward, I cannot see my actual ETH reward (which is 0.000015 ETH, or 0.00003) its showing only up to 3 decimals. 

maybe the hovered value should not be fixed to certain decimals? just let that be as big as it wants to be?

image

image

**Comment by kemuru** [comment]
> looks good, but I think it would look even better if we keep the units in the tooltip too 🤔 like `0.08 ETH` then you hover and you see `0.078 ETH` on the hover tooltip too 🤔 wdyt?

yes i agree with this also

**Comment by Harman-singh-waraich** [comment]
> when I hover on the ETH reward, I cannot see my actual ETH reward (which is 0.000015 ETH, or 0.00003) its showing only up to 3 decimals.
> 
> maybe the hovered value should not be fixed to certain decimals? just let that be as big as it wants to be?
> 
> image image

Yes, Just noticed the rewards formatting function has set decimals to 3 , fixing that

**Comment by Harman-singh-waraich** [comment]
> looks good, but I think it would look even better if we keep the units in the tooltip too 🤔 like `0.08 ETH` then you hover and you see `0.078 ETH` on the hover tooltip too 🤔 wdyt?

- Added `Unit` to `NumberDisplay`, also added a flag to not show unit while displaying formatted value(the one that shows normally), as in some place (Top Jurors) we don't show unit
- Also fixed coin value calculation in `Juror Rewards`

**Review by alcercu — APPROVED** [review]
lgtm

**Review by kemuru — APPROVED** [review]
lgtm

**Pull request merged**
